---
- name: Deploy a psql database with persistent storage
  hosts: localhost
  vars_prompt:
    - name: registry_username
      prompt: What is your registry_username?
      private: yes
      unsafe: yes
    - name: registry_password
      prompt: What is your registry_password?
      private: yes
      unsafe: yes
  tasks:

    - name: Create group 'postgres'
      ansible.builtin.group:
        name: postgres
        state: present
        gid: 26
      become: true
      

    - name: Create user 'postgres'
      ansible.builtin.user:
        name: postgres
        uid: 26
        group: postgres
      become: true

    - name: Create local directory
      ansible.builtin.file:
        path: /home/rodli/local
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'
      become: true

    - name: Create host directory
      ansible.builtin.file:
        path: /home/rodli/local/pgsql
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'
      become: true

    - name: Apply the container_file_t SELinux context for the host directory
      community.general.sefcontext:
        target: '/home/rodli/local/pgsql(/.*)?'
        setype: container_file_t
        state: present
      become: true
      notify: Apply new SELinux file context to the filesystem
# I had a problem with Ansible Python Interpreter.
# To overcome it, I set an environment variable in the commandline.
# -e 'ansible_python_interpreter=/usr/bin/python3'
# https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

    - name: Login to Red Hat Container Catalog
      containers.podman.podman_login:
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
        registry: registry.redhat.io
      changed_when: false

    - name: Pull image
      containers.podman.podman_image:
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
        name: registry.redhat.io/rhel8/postgresql-13:1-78.1665590937
        pull: yes
        state: present
        force: yes
# The image I want to pull can be found at https://catalog.redhat.com/software/containers/rhel8/postgresql-13/5ffdbdef73a65398111b8362
# https://bugzilla.redhat.com/show_bug.cgi?id=2020026
# https://developers.redhat.com/blog/2019/10/29/verifying-signatures-of-red-hat-container-images#testing_that_linux_container_tools_refuse_images_that_fail_signature_check

    - name: Run image
      containers.podman.podman_container:
        name: sharesdb
        image: rhel8/postgresql-13
        state: started
        #volume: 
        #  - /home/rodli/local/pgsql:/var/lib/pgsql/data
        env: 
          POSTGRESQL_USER: "rodli"
          POSTGRESQL_PASSWORD: "mypa55"
          POSTGRESQL_DATABASE: "sharesdb"
# $ podman logs d284c73188e5
# For general container run, you must either specify the following environment
# variables:
#   POSTGRESQL_USER  POSTGRESQL_PASSWORD  POSTGRESQL_DATABASE
# Or the following environment variable:
#   POSTGRESQL_ADMIN_PASSWORD
# Or both.

  handlers:
    - name: Apply new SELinux file context to the filesystem
      ansible.builtin.command: restorecon -irv /home/rodli/local/pgsql