---
- name: Deploy a psql database with persistent storage
  hosts: psql_database
  vars_prompt:
    - name: registry_username
      prompt: What is your registry_username?
      private: yes
    - name: registry_password
      prompt: What is your registry_password?
      private: yes
      unsafe: yes
  tasks:

    - name: Create local directory
      ansible.builtin.file:
        path: /home/rodli/local
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Create host directory
      ansible.builtin.file:
        path: /home/rodli/local/pgsql
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Apply the container_file_t SELinux context for the host directory
      community.general.sefcontext:
        target: '/home/rodli/local/pgsql(/.*)?'
        setype: container_file_t
        state: present
      notify: Apply new SELinux file context to the filesystem

    - name: Login to Red Hat Container Catalog
      containers.podman.podman_login:
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
        registry: registry.redhat.io

    - name: Pull image
      containers.podman.podman_image:
        name: registry.redhat.io/rhel8/postgresql-13
        pull: yes
        state: present

    - name: Run image
      containers.podman.podman_container:
        name: sharesdb
        image: registry.redhat.io/rhel8/postgresql-13
        state: started
        volume: /home/rodli/local/pgsql:/var/lib/pgsql/data
        env: 
          - PGUSER=rodli
          - PGPASSWORD=mypa55
          - PGDATABASE=sharesdb

  handlers:
    - name: Apply new SELinux file context to the filesystem
      ansible.builtin.command: restorecon -irv /home/rodli/local/pgsql